In [1]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
print(tf.__version__)

Instructions for updating:
non-resource variables are not supported in the long term


2.9.2


In [3]:
#Add a constant tensor to the graph
w1 = tf.ones((2,2))
# Add a variable to our graph
w2 = tf.Variable(tf.ones((2,2)))

with tf.Session() as sess:

  #initialize all variables
  sess.run(tf.global_variables_initializer())

  print(sess.run(w2))
  w3 = w1+w2
  print(sess.run(w3))

[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]


In [4]:
random_int_var = tf.get_variable("random_int_var_1_to_10",
                                 initializer = tf.random_uniform([3,3],
                                                                 minval=1,
                                                                 maxval=10,
                                                                 dtype=tf.int32))
random_int_var.shape

TensorShape([Dimension(3), Dimension(3)])

In [6]:
tf_int_ones = tf.ones(shape=[3,3], dtype="int32")
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(sess.run(random_int_var))
  print(sess.run(tf_int_ones))
  x = input("Type continue when ok")
  tf_matrix_multiplication_prod = tf.matmul(random_int_var, tf_int_ones)
  print(sess.run(tf_matrix_multiplication_prod))

[[2 4 9]
 [2 8 2]
 [8 2 3]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
Type continue when okcontinue
[[15 15 15]
 [12 12 12]
 [13 13 13]]
