In [ ]:
#Expression
# 2 x [13+(yx10) + (x+5)]

In [1]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
a = tf.constant(10)
b = tf.constant(20)
c = tf.multiply(a,b)
d = tf.add(a,b)
e = tf.subtract(a,b)
f = tf.placeholder(tf.int32)
g = tf.multiply(f,d)

In [4]:
x = int(input("Enter a number"))

sess = tf.Session()
print(sess.run(c))
print(sess.run(d))
print(sess.run(e))
print(sess.run(g,feed_dict={f:x}))
sess.close()

Enter a number4
200
30
-10
120


In [5]:
#Matrix mutiplication
mat1 = tf.constant([1,2,3,4,5,6,7,8,9],shape=[3,3])
mat2 = tf.constant([1,0,0,0,1,0,0,0,1],shape=[3,3])
op = tf.matmul(mat1,mat2)
sess = tf.Session()
print(sess.run(op))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
w1 = tf.ones((2,2))
w2 = tf.ones((2,2))
sess = tf.Session()
print(sess.run(w1))
print(sess.run(w2))
w3 = w1 + w2
print(sess.run(w3))
w4 = tf.ones((2,2))
w5 = tf.Variable(tf.ones((2,2)))
print(sess.run(w4))

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[2. 2.]
 [2. 2.]]
[[1. 1.]
 [1. 1.]]


In [8]:
#Node Representation
node1 = tf.constant(13)
node2 = tf.constant(5)
node3 = tf.placeholder(dtype=tf.int32)
node4 = tf.constant(10)
node5 = tf.placeholder(dtype=tf.int32)

node6 = tf.multiply(node2,node3)
node7 = tf.multiply(node4,node5)
node8 = tf.add(node6,node7)
node9 = tf.add(node1,node8)
node10 = tf.constant(2)
node11 = tf.multiply(node10,node9)

x = int(input("Please enter an integer"))
y = int(input("Please enter a second integer"))

sess = tf.Session()
print(sess.run(node11,feed_dict={node3:x, node5:y}))

Please enter an integer3
Please enter a second integer6
176
