In [ ]:
import numpy as np

In [ ]:
a = np.zeros((2,2))
a.shape

(2, 2)

In [ ]:
b = np.zeros((3,1))
b.shape

(3, 1)

In [ ]:
a.reshape(4,1)
print(a)
print(b)

[[0. 0.]
 [0. 0.]]
[[0.]
 [0.]
 [0.]]


In [ ]:
#Using tensorflow
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [ ]:
ta = tf.zeros((2,2)); tb = tf.ones((2,2))
print(ta)
# print(a)

Tensor("zeros_4:0", shape=(2, 2), dtype=float32)


In [ ]:
sess = tf.Session()
print(sess.run(ta))

[[0. 0.]
 [0. 0.]]


In [ ]:
a = tf.constant(2,name="a")
b = tf.constant(3,name="b")
c = tf.add(a,b,name="c")
print(c)

Tensor("c_1:0", shape=(), dtype=int32)


In [ ]:
sess = tf.Session()
print(sess.run(c))

5


In [ ]:
d = c + 5
sess = tf.Session()
print(sess.run(c))
sess = tf.Session()
print(sess.run(d))

5
10
